"""Benchmark: one change per request (how ableton-mcp works) vs one batch.

Builds the same template skeleton twice in the open Live set, cleaning up after
each run. The "naive" run sends every primitive op as its own request, so each
one pays a socket round trip plus a wait for Live's next main-thread tick —
the same cost structure as calling ableton-mcp's tools one clip at a time. In
real use each of those requests is also a separate Claude tool call, which is
far slower still; that part is estimated, not measured.
"""

from __future__ import annotations

import datetime as dt
import statistics
import time
from pathlib import Path

from . import templates as tpl
from .connection import LiveConnection, LiveError
from .plan import compile_plan, skeleton_plan

DOC = Path(__file__).resolve().parents[2] / "docs" / "benchmarks.md"


def _cleanup(live: LiveConnection, track_count: int, locator_times: set[float]) -> None:
    snap = live.snapshot(include_devices=False)
    ops = [{"op": "delete_track", "track": i} for i in range(len(snap["tracks"]) - 1, track_count - 1, -1)]
    ops += [{"op": "delete_locator", "time": c["time"]} for c in snap["locators"]
            if round(c["time"], 3) not in locator_times]
    if ops:
        result = live.run_ops(ops)
        if result["errors"]:
            print("Cleanup errors:", result["errors"][:5])


def run_benchmark(args) -> int:
    live = LiveConnection()
    try:
        info = live.ping()
    except LiveError as e:
        print(e)
        return 1

    snap = live.snapshot(include_devices=False)
    if not args.yes:
        print(f"This adds and then removes tracks and locators in the open set "
              f"({len(snap['tracks'])} tracks now). Best run in a new, empty set.")
        if input("Continue? [y/N] ").strip().lower() != "y":
            return 1

    base_tracks = len(snap["tracks"])
    base_locators = {round(c["time"], 3) for c in snap["locators"]}
    original_tempo = snap["tempo"]

    pings = []
    for _ in range(20):
        t = time.perf_counter()
        live.ping()
        pings.append((time.perf_counter() - t) * 1000)
    ping_ms = statistics.median(pings)

    arr = tpl.compile_arrangement(tpl.load_template(args.genre), args.variant)
    plan = skeleton_plan(arr, snap, set_tempo=False)
    ops = compile_plan(plan, snap).ops
    print(f"{arr.template.name} {args.variant}: {len(ops)} ops "
          f"({len(plan['tracks'])} tracks, {len(plan['clips'])} clips, {len(plan['locators'])} locators)")

    print("Naive run (one request per op)...")
    errors = 0
    t = time.perf_counter()
    for op in ops:
        errors += len(live.run_ops([op])["errors"])
    naive_s = time.perf_counter() - t
    _cleanup(live, base_tracks, base_locators)

    print("Batch run (one request)...")
    t = time.perf_counter()
    result = live.run_ops(ops)
    batch_s = time.perf_counter() - t
    batch_errors = len(result["errors"])
    _cleanup(live, base_tracks, base_locators)
    live.run_ops([{"op": "set_tempo", "bpm": original_tempo}])

    llm_s = len(ops) * args.seconds_per_tool_call
    rows = [
        ("Round trip (median of 20 pings)", f"{ping_ms:.1f} ms", ""),
        ("Naive: one request per op", f"{naive_s:.2f} s", f"{len(ops)} requests, {errors} errors"),
        ("Batch: one request", f"{batch_s:.2f} s",
         f"main thread {result.get('main_thread_ms')} ms, {batch_errors} errors"),
        ("Speed-up (plumbing only)", f"{naive_s / batch_s:.1f}×" if batch_s else "—", ""),
        ("Estimated with Claude calling a tool per op", f"~{llm_s / 60:.0f} min",
         f"{len(ops)} tool calls × {args.seconds_per_tool_call:g} s (estimate, not measured)"),
        ("Estimated with Claude calling build_skeleton once", f"~{batch_s + args.seconds_per_tool_call:.0f} s",
         "1 tool call"),
    ]
    width = max(len(r[0]) for r in rows)
    print()
    for label, value, note in rows:
        print(f"{label:<{width}}  {value:>10}  {note}")

    if not args.no_write:
        DOC.parent.mkdir(exist_ok=True)
        new = not DOC.exists()
        with DOC.open("a") as f:
            if new:
                f.write("# Benchmarks\n\nGenerated by `uv run ableton-helper bench`. "
                        "See src/ableton_helper/bench.py for what is measured.\n")
            f.write(f"\n## {dt.date.today()} — {arr.template.name} {args.variant}, "
                    f"Live {info.get('live_version')}\n\n")
            f.write(f"{len(ops)} ops: {len(plan['tracks'])} tracks, {len(plan['clips'])} clips, "
                    f"{len(plan['locators'])} locators.\n\n| Measure | Result | Notes |\n|---|---|---|\n")
            for label, value, note in rows:
                f.write(f"| {label} | {value} | {note} |\n")
        print(f"\nAppended to {DOC}")
    return 0
